# SoftRelTools GNUmakefile for MySim top level

# Compile the files in src subdirectory
SUBDIRS=src dict

# Header files go in include subdirectory
PACKAGE_INCLUDE=RawObjs

################################
include SoftRelTools/standard.mk

