# SoftRelTools GNUmakefile for MySim top level

# Compile the files in src subdirectory
SUBDIRS=src

# Header files go in include subdirectory
PACKAGE_INCLUDE=DAQTrigger

################################
include SoftRelTools/standard.mk

