#############################################################
# example Makefile for linking 
# uses SoftRelTools/standard.mk
#############################################################

BINS =  BuildMuonObjs

SIMPLEBINS = $(BINS) 

#framework general 

override LOADLIBES += -lMuonObjs

############################################################
include SoftRelTools/standard.mk
include SoftRelTools/arch_spec_root.mk
