#############################################################
# example Makefile for linking 
# uses SoftRelTools/standard.mk
#############################################################

BINS =  BuildDAQTrigger

SIMPLEBINS = $(BINS) 

#framework general 

override LOADLIBES += -lDAQTrigger

############################################################
include SoftRelTools/standard.mk
include SoftRelTools/arch_spec_root.mk
