#############################################################
# example Makefile for linking 
# uses SoftRelTools/standard.mk
#############################################################

BINS =  BuildOnlObjs

SIMPLEBINS = $(BINS) 

#framework general 

override LOADLIBES += -lOnlObjs

############################################################
include SoftRelTools/standard.mk
include SoftRelTools/arch_spec_root.mk
