#############################################################
# example Makefile for linking 
# uses SoftRelTools/standard.mk
#############################################################

BINS = 

SIMPLEBINS = $(BINS) 

#framework general 

override LOADLIBES += -lRawObjs

############################################################
include SoftRelTools/standard.mk
include SoftRelTools/arch_spec_root.mk
