[program:muonmon]
#command=/etc/supervisord.d/test.sh
#command=/etc/supervisord.d/amore2mon.sh
command=/home/cupsoft/monitoring/rel/amore2mon.sh
user=cupsoft
#command=/home/gowoon/influxDB/amore2mon.sh
#command=/bin/bash -c ". /etc/supervisord.d/test.sh"
